const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../core');
const context={heading:'Contact us',fields:[{id:'f0',kind:'text',label:'Name'},{id:'f1',kind:'text',label:'Company'}]};
test('every independent question names its actual target field',()=>{const b=C.build('Name: Alex Morgan\nCompany: Northstar Studio',context);assert.match(b.body.questions.f0.instructions,/"Name"/);assert.match(b.body.questions.f1.instructions,/"Company"/);assert.notEqual(b.body.questions.f0.instructions,b.body.questions.f1.instructions);});
function stage(text){const span={id:'s0',text,start:0,end:text.length};return C.boundaries(text,context,[{id:'f0',confident:true,selected:'s0',options:[span]},{id:'f1',confident:true,selected:'s0',options:[span]}]);}
function answer(stage,id,value){const {tokens,span}=stage.items.find(i=>i.field.id===id),start=span.text.indexOf(value),end=start+value.length;return {[id+'_start']:{type:'choice',probabilities:{['w'+tokens.findIndex(t=>t.index===start)]:.99}},[id+'_end']:{type:'choice',probabilities:{['w'+tokens.findIndex(t=>t.index+t.segment.length===end)]:.99}}};}
test('boundary decisions can extract names and companies from arbitrary prose as exact slices',()=>{const text='Hi, I’m Zoë García from Café Étoile. Please contact me.',s=stage(text);const values=C.extracted(text,s,{...answer(s,'f0','Zoë García'),...answer(s,'f1','Café Étoile')});assert.deepEqual(values.map(v=>v.text),['Zoë García','Café Étoile']);for(const v of values)assert.equal(text.slice(v.start,v.end),v.text);assert.ok(C.verifiedRows(context,values,{f0:{type:'noul',noul:.99},f1:{type:'noul',noul:.99}}).every(r=>r.confident));});
test('unknown, reversed, uncertain boundaries cannot produce values',()=>{const s=stage('Alex Morgan works here.');assert.equal(C.extracted('Alex Morgan works here.',s,{f0_start:{type:'choice',probabilities:{w999:.99}},f0_end:{type:'choice',probabilities:{w1:.99}}}).length,0);assert.equal(C.extracted('Alex Morgan works here.',s,{f0_start:{type:'choice',probabilities:{w2:.99}},f0_end:{type:'choice',probabilities:{w0:.99}}}).length,0);});
test('final verification fails closed and rejects duplicate values across distinct fields',()=>{const values=context.fields.map(field=>({field,text:'Alex Morgan',start:0,end:11}));assert.ok(C.verifiedRows(context,values,{f0:{type:'noul',noul:.99},f1:{type:'noul',noul:.99}}).every(r=>!r.confident));assert.ok(C.verifiedRows(context,values.slice(0,1),{}).every(r=>!r.confident));assert.ok(C.verifiedRows(context,values.slice(0,1),{f0:{type:'noul',noul:.6}}).every(r=>!r.confident));});
test('observed prose boundary scores reach verification without bypassing it',()=>{const text='Hi, I’m Alex Morgan from Northstar Studio.',s=stage(text),answers={...answer(s,'f0','Alex Morgan'),...answer(s,'f1','Northstar Studio')};for(const a of Object.values(answers))a.probabilities[Object.keys(a.probabilities)[0]]=.68;const values=C.extracted(text,s,answers);assert.equal(values.length,2);assert.ok(C.verifiedRows(context,values,{}).every(r=>!r.confident));assert.ok(C.verifiedRows(context,values,{f0:{type:'noul',noul:.98},f1:{type:'noul',noul:.98}}).every(r=>r.confident));});
test('typed email field cannot choose a surrounding sentence',()=>{const f={id:'f0',kind:'email',label:'Email'},b=C.build('You can reach me at alex@example.com.',{heading:'Contact',fields:[f]});const choices=Object.values(b.body.questions.f0.criteria);assert.deepEqual(choices,['No suitable passage','alex@example.com']);});
test('multiline labelled descriptions remain complete exact passages',()=>{
 const text='Title: Keep drafts\nDescription: Preserve the title.\nPreserve the description too.\n\nKeep attachments until discarded.\nCompany: Northstar Studio';
 const b=C.build(text,{heading:'New issue',fields:[{id:'f0',kind:'description',label:'Description'}]});
 const span=b.spans.find(s=>s.label==='Description');assert.equal(span.text,'Preserve the title.\nPreserve the description too.\n\nKeep attachments until discarded.');assert.equal(text.slice(span.start,span.end),span.text);assert.ok(Object.values(b.body.questions.f0.criteria).includes('Description: '+span.text));
});
test('embedded email in structured content retains its destination',()=>{
 const text='Linear ticket Title: Contact bug Description: Email alex@example.com about the issue. Calendar event Title: Demo Description: Email zoe@example.com for the event.';
 const field={id:'f0',kind:'email',label:'Email'},b=C.build(text,{heading:'New issue',fields:[field]});
 const email=b.spans.find(s=>s.text==='alex@example.com');assert.ok(email);assert.equal(email.destination,'Linear ticket');assert.equal(text.slice(email.start,email.end),email.text);assert.ok(!Object.values(b.body.questions.f0.criteria).some(s=>s.includes('zoe@example.com')));
});
test('invalid readiness cannot authorize a passage',()=>{const fields=[{id:'f0',kind:'text',label:'Name'}],b=C.build('Alex Morgan',{heading:'Contact',fields});for(const value of [Infinity,1.1,NaN])assert.equal(C.resolve({f0:{type:'choice',probabilities:{s0:.99}},ready:{type:'noul',noul:value}},b.spans,fields)[0].confident,false);});
