const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');const C=require('../core.js');
function harness(consent=true){let listener,changed,installed;const store={},calls=[],settings={key:'test-key',consent};let fetchHook;const notices=[];const context={SmartPasteCore:C,importScripts(){},crypto:{randomUUID:()=> 'v1'},AbortController,DOMException,setTimeout,clearTimeout,performance,fetch:async(url,request)=>{
 calls.push({url,request});if(fetchHook)await fetchHook(calls.length,request);const body=JSON.parse(request.body);if(body.state.passages){const answers={};for(const [id,q] of Object.entries(body.questions)){const keys=Object.keys(q.criteria).filter(k=>k!=='none');answers[id]={type:'choice',probabilities:{[id.endsWith('_start')?keys[0]:keys.at(-1)]:.99}};}return {ok:true,json:async()=>({answers})};}if(body.state.proposed)return {ok:true,json:async()=>({answers:Object.fromEntries(Object.keys(body.questions).map(id=>[id,{type:'noul',noul:.99}]))})};return {ok:true,json:async()=>({model:'jev-test',answers:{f0:{type:'choice',probabilities:{s0:.99,none:.01}},ready:{type:'noul',noul:.99}}})};},chrome:{
 action:{onClicked:{addListener(){}},setBadgeText:async()=>{},setTitle:async()=>{}},storage:{onChanged:{addListener(fn){changed=fn;}},local:{setAccessLevel:async()=>{},get:async()=>({...settings})},session:{setAccessLevel:async()=>{},get:async()=>store,set:async obj=>Object.assign(store,obj),remove:async key=>delete store[key]}},tabs:{query:async()=>[{id:1}],sendMessage:async(id,m)=>notices.push(m)},runtime:{getURL:()=> 'chrome-extension://test/',openOptionsPage:async()=>notices.push("settings"),onInstalled:{addListener(fn){installed=fn;}},onMessage:{addListener(fn){listener=fn;}}}}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../worker.js'),'utf8'),context);
 return {calls,store,settings,notices,change:(c,a)=>changed(c,a),install:reason=>installed({reason}),hook:fn=>fetchHook=fn,send:(m,url='chrome-extension://test/popup.html')=>new Promise(resolve=>listener(m,{url,tab:{id:1}},resolve))};
}
test('capture stays in session; preparation uses actual context and source text',async()=>{const h=harness();assert.equal((await h.send({type:'capture',text:'Fix the draft bug.'})).ok,true);assert.equal(h.calls.length,0);const r=await h.send({type:'prepare',version:'v1',context:{heading:'New issue',fields:[{id:'f0',kind:'title',label:'Issue title',focused:true,occupied:false}]}},'https://linear.app/acme');assert.equal(h.calls.length,3);const req=JSON.parse(h.calls[0].request.body);assert.equal(req.state.form.heading,'New issue');assert.equal(req.state.clipboard,'Fix the draft bug.');assert.equal(r.rows[0].confident,true);assert.equal(r.rows[0].options[0].text,'Fix the draft bug.');});
test('no remote preparation without consent',async()=>{const h=harness(false);await h.send({type:'capture',text:'Fix the draft bug.'});const r=await h.send({type:'prepare',version:'v1',context:{fields:[{id:'f0',kind:'title'}]}},'https://linear.app/acme');assert.match(r.error,/enable matching/);assert.equal(h.calls.length,0);});
test('a page cannot replace clipboard capture; stale capture is rejected',async()=>{const h=harness();assert.match((await h.send({type:'capture',text:'Fake capture'},'https://linear.app/acme')).error,/extension button/);await h.send({type:'capture',text:'Fix the draft bug.'});assert.match((await h.send({type:'prepare',version:'old',context:{fields:[{id:'f0',kind:'title'}]}},'https://linear.app/acme')).error,/capture changed/);assert.equal(h.calls.length,0);});

test('configured API key cannot be captured or returned from stale session data',async()=>{
 const h=harness();const r=await h.send({type:'capture',text:'test-key'});assert.match(r.error,/Your key is saved/);assert.equal(h.store.capture,undefined);
 h.store.capture={text:'prefix test-key suffix',version:'v1'};const status=await h.send({type:'status'});assert.equal(status.capture,undefined);assert.equal(h.store.capture,undefined);assert.equal(h.calls.length,0);
});
test('generic form matching works on another website and validates field metadata',async()=>{
 const h=harness();await h.send({type:'capture',text:'Email: alex@example.com'});
 const r=await h.send({type:'prepare',version:'v1',context:{heading:'Contact',fields:[{id:'f0',kind:'email',label:'Email',focused:true,occupied:false}]}},'https://example.org/contact');assert.ok(r.rows);assert.equal(h.calls.length,3);assert.ok(!JSON.stringify(h.calls[0]).includes('Linear'));
 const invalid=await h.send({type:'prepare',version:'v1',context:{fields:[{id:'f0',kind:'password',label:'Password'}]}},'https://example.org/contact');assert.match(invalid.error,/Unsupported/);assert.equal(h.calls.length,3);
});
const form={heading:'Contact',fields:[{id:'f0',kind:'text',label:'Name'}]};
test('revoking matching during a request cancels it and notifies existing tabs',async()=>{const h=harness();await h.send({type:'capture',text:'Alex Morgan'});h.hook(async n=>{if(n===1){h.settings.consent=false;h.change({consent:{oldValue:true,newValue:false}},'local');}});const r=await h.send({type:'prepare',version:'v1',context:form});assert.match(r.error,/cancelled|changed/);assert.equal(h.calls.length,1);assert.ok(h.notices.some(n=>n.type==='captureChanged'));});
test('capture replacement during final verification cannot return a usable result',async()=>{const h=harness();await h.send({type:'capture',text:'Alex Morgan'});h.hook(async n=>{if(n===3)h.store.capture={text:'Different person',version:'v2'};});const r=await h.send({type:'prepare',version:'v1',context:form});assert.match(r.error,/changed/);assert.equal(r.rows,undefined);});
test('extension updates do not reopen settings; first install does',async()=>{const h=harness();await h.install('update');assert.ok(!h.notices.includes('settings'));await h.install('install');assert.ok(h.notices.includes('settings'));});

test('current paste uses fresh text without replacing old capture',async()=>{const h=harness();await h.send({type:'capture',text:'Old capture'});const r=await h.send({type:'preparePaste',text:'Fresh prose',version:'paste-1',context:form},'https://example.org');assert.equal(r.version,'paste-1');assert.equal(JSON.parse(h.calls[0].request.body).state.clipboard,'Fresh prose');assert.equal(h.store.capture.text,'Old capture');});
test('direct paste still rejects credentials and disabled matching',async()=>{for(const consent of [true,false]){const h=harness(consent);const r=await h.send({type:'preparePaste',text:'test-key',version:'paste-1',context:form});assert.ok(r.error);assert.equal(h.calls.length,0);}});
